# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'cnt'
    subscriptionId: '7c71b563-0dc0-4bc0-bcf6-06f8f0516c7a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'template-alt-rg'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/ARMTemplates/template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/ARMTemplates/parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'output'