# This is a basic workflow to help you get started with Actions

name: Load Test

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "demo-ninallam"    # set this to your application's name
  LOAD_TEST_RESOURCE: "new-resource-ado"
  LOAD_TEST_RESOURCE_GROUP: "new-resource-ado-rg"
  LOAD_TEST_LOCATION: "East US"
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.15.1'                # set this to the node version to use
  LOCATION: "West US"
  APPINSIGHTLOCATION: "West US"
  DATABASEACCOUNTLOCATION: "westus"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  loadtest:
    name: Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1.0.8
        with:
          loadTestConfigFile: 'SampleApp.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
          env: | 
            [
              {
                "name": "webapp",
                "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
